tinyMCE.init({
	mode : "exact",
	elements: "rich",
	theme : "advanced",
	language:"en",
	plugins : "advlink,autolink,lists,spellchecker,pagebreak,style,layer,table,save,advhr,advimage,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
	// Theme options
	theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,cut,copy,paste,pastetext,pasteword,|,bullist,numlist,|,undo,redo,|,link,unlink,anchor,image,cleanup|sub,sup,|,spellchecker,fullscreen,code",
	theme_advanced_buttons2:"",
	theme_advanced_buttons3:"",
	theme_advanced_source_editor_width: "900",
	theme_advanced_toolbar_location : "top",
	theme_advanced_toolbar_align : "left",
	theme_advanced_statusbar_location : "bottom",
	theme_advanced_resizing : false,
	plugi2n_insertdate_dateFormat : "%Y-%m-%d",
	plugi2n_insertdate_timeFormat : "%H:%M:%S",
	paste_auto_cleanup_on_paste : true,
	paste_convert_headers_to_strong : false,
	paste_strip_class_attributes : "all",
	paste_remove_spans : false,
	paste_remove_styles : true,
	paste_retain_style_properties : "color,font-size, width, height",
	inline_styles : false,
	relative_urls : false,
	convert_urls: false,
        skin : "o2k7",
        skin_variant : "silver",
	external_link_list_url : "http://sushimgn.ru/filemanager/list_url",
	external_image_list_url : "http://sushimgn.ru/filemanager/list_img",
});