--
DROP TABLE IF EXISTS #PX#_admin_menu_items;
--
CREATE TABLE #PX#_admin_menu_items (
item_id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT "Menu item ID",
menu_type TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT "Menu type",
menu_name CHAR(30) NOT NULL DEFAULT 'NoName' COMMENT "Visible menu name",
uri VARCHAR(90) NOT NULL DEFAULT '',
priority TINYINT UNSIGNED NOT NULL DEFAULT 0,
active BOOL NOT NULL DEFAULT FALSE,
icon CHAR(30) NOT NULL DEFAULT ''
) ENGINE='INNODB';